baseURL: https://bhalaji.com/
title: Bhalaji Yadav Kantepalle
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
paginate: 10
paginatePath: /page/
outputs:
  home:
  - HTML
  - RSS
  section:
  - HTML
  - RSS
imaging:
  quality: 75
  resampleFilter: lanczos
  anchor: smart
taxonomies:
  tag: tags
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
  - name: tags
    weight: 100
security:
  funcs:
    getenv:
    - ^HUGO_
markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: false
    noClasses: false
    style: monokai
    tabWidth: 4
sitemap:
  changefreq: monthly
  priority: 0.6
  filename: sitemap.xml
