# Languages
en:
  languageCode: en-us
  contentDir: content
  title: Bhalaji Kantepalle
  params:
    description: Research portfolio of Bhalaji Yadav Kantepalle
  menu:
    main:
      - name: Home
        url: /#about
        weight: 10
      - name: Research
        url: /#research
        weight: 20
      - name: Outputs
        url: /#outputs
        weight: 30
      - name: Presentations
        url: /#presentations
        weight: 40
      - name: Service
        url: /#service
        weight: 50
      
      - name: Contact
        url: /#contact
        weight: 60
