# Languages
en:
  languageCode: en-us
  contentDir: content
  title: Bhalaji Yadav
  params:
    description: Portfolio of Bhalaji Yadav - Chemical Engineer
  menu:
    main:
      - name: Home
        url: /#about
        weight: 10
      - name: News
        url: /#news
        weight: 20
      - name: Projects
        url: /#projects
        weight: 30
      - name: Publications
        url: /#publications
        weight: 40
      - name: Experience
        url: /#experience
        weight: 50
      - name: Contact
        url: /#contact
        weight: 60
      - name: CV
        url: uploads/resume.pdf
        weight: 70
